---
title: "Writing Conditional Statements and Loops"
output: html_notebook
---

# Define the data
```{r}
cust_df <- data.frame(ProdScores = c(5.7, 7.2, 8.9, 4.0, 6.1, 6.1),
                      ServScores = c(9.2, 4.0, 4.0, 4.5, 8.9, 5.2),
                      Return = factor(c("Yes", "No", "No",
                                        "Yes", "Yes", "Yes")))
cust_df
```
# Generate a suggested action based on customer behavior
```{r}
cust_prod <- cust_df$ProdScores[1]
cust_ret <- cust_df$Return[1]

if (cust_prod > 8.0 & cust_ret == "No") {
  print("Find out why customer is not returning.")
} else if (cust_prod < 8.0 & cust_ret == "Yes") {
  print("Contact customer about product quality.")
} else {
  print("Offer deal to entice customer.")
}
```
# Report all customer service scores
```{r}
cust_srv <- cust_df$ServScores
count <- 1

while (count <= length(cust_srv)) {
  msg <- paste("Customer", count, "service score:", cust_srv[count])
  
  print(msg)
  count <- count + 1
}
```
# Get return status for all customers except those with high service scores
```{r}
count <- 1

for (i in cust_srv) {
  
  if (i > 8.0) {
    count <- count + 1
    next
  } else if (i < 4.0) {
    print("Service score can't be less than 4. Exiting...")
    break
  } else {
    print(as.character(cust_df[count, "Return"]))
  }
  
  count <- count + 1
}
```
# Generate suggested actions for all customers
```{r}
cust_prod <- cust_df$ProdScores
cust_ret <- cust_df$Return
count <- 1

for (i in cust_prod) {
  msg_start <- paste0("Customer ", count, ":")
  
  if (i > 8.0 & cust_ret[count] == "No") {
    msg <- paste(msg_start, "Find out why customer is not returning.")
  } else if (i < 8.0 & cust_ret[count] == "Yes") {
    msg <- paste(msg_start, "Contact customer about product quality.")
  } else {
    msg <- paste(msg_start, "Offer deal to entice customer.")
  }
  
  print(msg)
  count <- count + 1
}
```